# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  _target_: {{cookiecutter.project_slug}}.utils.smart_rich_progress.SmartRichProgressBar
